# Generated by Django 4.2 on 2023-04-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=90)),
                ('img_Link', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
